name: "docker-build-push-coder-minimal"

on:
  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      WORKING_DIR: coder
      DOCKERFILE_NAME: minimal.Dockerfile
      IMAGE_NAME: tuana9a/coder
      IMAGE_TAG_PREFIX: minimal-
      tag-commithash: false
      tag-monthly: true
      tag-daily: true
      tag-secondly: true
      push: true
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
